name: Check possible dependency update.
description: Check a dependency for an update, open/update/close a PR if needed.

inputs:
  repo_path:
    type: string
    required: true
    description: "the one that looks like 'github.com/remerge/xyz'"
  repo_name:
    type: string
    required: true
    description: "the one that looks like 'remerge/xyz'"
  personal_access_token:
    description: "Need a PAT with update permissions to send events to a repo"
    required: true
  ssh_key:
    description: "Need an SSH key to fetch private repos"
    required: true

runs:
  using: composite
  steps:
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ inputs.ssh_key }}

    - name: Set global git config
      shell: bash
      run: git config --global url.git@github.com:.insteadof https://github.com/

    - name: Check out
      uses: actions/checkout@v3

    - shell: bash
      env:
        GOPRIVATE: github.com/remerge
        GO111MODULE: on
      run: |
        go get ${{ inputs.repo_path }}
        go mod tidy
        git diff

    - name: Create or update pull request to update ${{ inputs.repo_name }}
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ inputs.personal_access_token }}
        commit-message: Update ${{ inputs.repo_name }}
        committer: Dependency Updater <tech@remerge.io>
        author: Dependency Updater <tech@remerge.io>
        signoff: false
        branch: update-${{ inputs.repo_name }}
        delete-branch: true
        title: Update ${{ inputs.repo_name }}
        body: |
          `go get ${{ inputs.repo_path }} && go mod tidy`
        labels: depupdater
