name: Check possible dependency update.
description: Check a dependency for an update, open/update/close a PR if needed.

inputs:
  repo_path:
    required: true
    description: "the one that looks like 'github.com/remerge/xyz'"
  repo_name:
    required: true
    description: "the one that looks like 'remerge/xyz'"
  assign_to:
    required: true
    description: "Github username we should assign the PR to"
  app_id:
    description: "App id that we exchange for a token."
    required: true
  app_key:
    description: "Private app key that we can exchange for a token."
    required: true
  ssh_key:
    description: "Need an SSH key to fetch private repos"
    required: true
  gpg_private_key:
    description: "Need GPG private key for signing commits"
    required: false
  gpg_passphrase:
    description: "Need GPG passphrase key for signing commits"
    required: false
  go_private:
    description: "Go private value"
    required: false
  commiter_name:
    description: "Name of the commiter"
    required: true
  commiter_email:
    description: "email of the commiter, without <>. If gpg_passpharse is used, commiter email must match gpg key's eamil"
    required: true

runs:
  using: composite
  steps:
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ inputs.ssh_key }}

    - name: Set global git config
      shell: bash
      run: git config --global url.git@github.com:.insteadof https://github.com/

    - name: Check out
      uses: actions/checkout@v3

    - run: echo "GO_VERSION=$(grep '^go ' < go.mod | awk '{print $2}')" >> "$GITHUB_ENV"
      shell: bash

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - shell: bash
      env:
        GOPRIVATE: ${{ inputs.go_private }}
        GO111MODULE: on
      run: |
        go get ${{ inputs.repo_path }}
        go mod tidy
        git diff

    - name: Use our App Key to get an App Token
      id: generate_app_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{  inputs.app_id }}
        private_key: ${{ inputs.app_key }}

        # Optional (defaults to all the Github App permissions).
        # Using a YAML multiline string to avoid escaping the JSON quotes.
        # permissions: >-
        #   {"members": "read"}

        # Optional (defaults to the current repository).
        # repository: "owner/repo"
    - uses: crazy-max/ghaction-import-gpg@v3
      if: ${{ inputs.gpg_private_key !== '' && inputs.gpg_private_key !== null }}
      with:
        gpg-private-key: ${{ inputs.gpg_private_key }}
        passphrase: ${{ inputs.gpg_passphrase }}
        git-user-signingkey: true
        git-commit-gpgsign: true

    - name: Create or update pull request to update ${{ inputs.repo_name }}
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ steps.generate_app_token.outputs.token }}
        commit-message: Update ${{ inputs.repo_name }}
        committer: "${{ inputs.commiter_name }} <${{ inputs.commiter_email }}>"
        author: "${{ inputs.commiter_name }} <${{ inputs.commiter_email }}>"
        signoff: false
        branch: update-${{ inputs.repo_name }}
        delete-branch: true
        title: Update ${{ inputs.repo_name }}
        body: |
          `go get ${{ inputs.repo_path }} && go mod tidy`
        labels: depupdater
        assignees: ${{ inputs.assign_to }}
